import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { request } from '@/src/api';
import { Empty, Screen } from '@/src/components';
import { useAuth } from '@/src/store';
import { colors } from '@/src/theme';
type Training = { id: string; startsAt: string; type: string; category: { nameAr: string }; facility?: { nameAr: string } | null };
type Match = { id: string; kickoffAt: string; opponent: string; competition: string; category: { nameAr: string }; stadium?: string | null };
type Event = { id: string; date: string; title: string; detail: string; place?: string | null; kind: 'training' | 'match' };
export default function Calendar() {
  const token = useAuth((state) => state.token);
  const query = useQuery({ queryKey: ['mobile-calendar'], queryFn: async () => { const [trainings, matches] = await Promise.all([request<{ data: Training[] }>('/trainings', {}, token), request<{ data: Match[] }>('/matches', {}, token)]); return [...trainings.data.map((item): Event => ({ id: `t-${item.id}`, date: item.startsAt, title: 'حصة تدريبية', detail: `${item.category.nameAr} · ${item.type.replaceAll('_', ' ')}`, place: item.facility?.nameAr, kind: 'training' })), ...matches.data.map((item): Event => ({ id: `m-${item.id}`, date: item.kickoffAt, title: `USN × ${item.opponent}`, detail: `${item.category.nameAr} · ${item.competition}`, place: item.stadium, kind: 'match' }))].sort((a, b) => +new Date(a.date) - +new Date(b.date)); } });
  return <Screen><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => query.refetch()} tintColor={colors.gold} />}><Text style={styles.kicker}>USN CALENDAR</Text><Text style={styles.title}>{'البرنامج'}</Text><Text style={styles.subtitle}>{'التدريبات والمباريات القادمة'}</Text>{query.data?.length ? <View style={styles.list}>{query.data.map((event) => <View key={event.id} style={styles.event}><View style={[styles.icon, event.kind === 'match' && styles.matchIcon]}><Ionicons name={event.kind === 'match' ? 'trophy-outline' : 'fitness-outline'} color={event.kind === 'match' ? colors.navy950 : colors.gold} size={20} /></View><View style={styles.content}><Text style={styles.eventTitle}>{event.title}</Text><Text style={styles.detail}>{event.detail}</Text>{event.place && <Text style={styles.place}><Ionicons name="location-outline" /> {event.place}</Text>}</View><View style={styles.date}><Text style={styles.day}>{new Date(event.date).toLocaleDateString('ar-TN', { day: '2-digit' })}</Text><Text style={styles.month}>{new Date(event.date).toLocaleDateString('ar-TN', { month: 'short' })}</Text><Text style={styles.time}>{new Date(event.date).toLocaleTimeString('ar-TN', { hour: '2-digit', minute: '2-digit' })}</Text></View></View>)}</View> : <Empty text={query.isLoading ? 'جار التحميل…' : 'لا توجد أنشطة مبرمجة'} />}</ScrollView></Screen>;
}
const styles = StyleSheet.create({ kicker: { color: colors.gold, textAlign: 'right', fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginTop: 8 }, title: { color: colors.white, textAlign: 'right', fontSize: 29, fontWeight: '900', marginTop: 8 }, subtitle: { color: colors.muted, textAlign: 'right', fontSize: 12, marginTop: 5, marginBottom: 24 }, list: { gap: 10 }, event: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.navy900, borderRadius: 17, padding: 14 }, icon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(243,189,34,.1)' }, matchIcon: { backgroundColor: colors.gold }, content: { flex: 1 }, eventTitle: { color: colors.white, textAlign: 'right', fontSize: 14, fontWeight: '800' }, detail: { color: colors.muted, textAlign: 'right', fontSize: 10, marginTop: 4 }, place: { color: colors.muted, textAlign: 'right', fontSize: 9, marginTop: 5 }, date: { borderRightWidth: 1, borderRightColor: colors.line, paddingRight: 11, alignItems: 'center', minWidth: 50 }, day: { color: colors.gold, fontSize: 20, fontWeight: '900' }, month: { color: colors.muted, fontSize: 9 }, time: { color: colors.white, fontSize: 8, marginTop: 4 } });
