import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { request } from '@/src/api';
import { Card, Empty, Screen } from '@/src/components';
import { useAuth } from '@/src/store';
import { colors } from '@/src/theme';
type Overview = { stats: { players: number; injured: number }; upcomingTrainings: Array<{ id: string; startsAt: string; category: { nameAr: string } }>; upcomingMatches: Array<{ id: string; kickoffAt: string; opponent: string }> };
type Summary = { attendanceRate: number; marked: number; present: number };
type Announcement = { id: string; titleAr: string; messageAr: string; priority: string };
export default function Home() {
  const { token, user } = useAuth(); const query = useQuery({ queryKey: ['mobile-home'], queryFn: async () => { const [overview, attendance, announcements, notifications] = await Promise.all([request<{ data: Overview }>('/dashboard/overview', {}, token), request<{ data: Summary }>('/trainings/statistics/attendance', {}, token), request<{ data: Announcement[] }>('/announcements', {}, token), request<{ meta: { unread: number } }>('/notifications', {}, token)]); return { overview: overview.data, attendance: attendance.data, announcement: announcements.data[0], unread: notifications.meta.unread }; } }); const data = query.data;
  return <Screen><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => query.refetch()} tintColor={colors.gold} />}><View style={styles.heading}><View><Text style={styles.kicker}>USN · 2026/2027</Text><Text style={styles.title}>{'مرحبا بك،'}</Text><Text style={styles.name}>{user?.displayName ?? 'عضو النادي'}</Text></View><View style={styles.bell}><Ionicons name="notifications-outline" color={colors.gold} size={21} />{Boolean(data?.unread) && <Text style={styles.badge}>{data?.unread}</Text>}</View></View>
    <View style={styles.stats}><Card><Text style={styles.number}>{data?.overview.stats.players ?? '—'}</Text><Text style={styles.label}>{'لاعب'}</Text></Card><Card><Text style={[styles.number, { color: colors.green }]}>{data ? `${data.attendance.attendanceRate}%` : '—'}</Text><Text style={styles.label}>{'نسبة الحضور'}</Text></Card><Card><Text style={[styles.number, { color: colors.red }]}>{data?.overview.stats.injured ?? '—'}</Text><Text style={styles.label}>{'مصاب'}</Text></Card></View>
    <Text style={styles.section}>{'الحصة القادمة'}</Text>{data?.overview.upcomingTrainings[0] ? <Card><View style={styles.eventRow}><View style={styles.eventIcon}><Ionicons name="fitness-outline" size={21} color={colors.gold} /></View><View style={{ flex: 1 }}><Text style={styles.eventTitle}>{data.overview.upcomingTrainings[0].category.nameAr}</Text><Text style={styles.label}>{new Date(data.overview.upcomingTrainings[0].startsAt).toLocaleString('ar-TN')}</Text></View></View></Card> : <Empty text={'لا توجد حصة مبرمجة'} />}
    <Text style={styles.section}>{'المباراة القادمة'}</Text>{data?.overview.upcomingMatches[0] ? <Card><View style={styles.eventRow}><View style={[styles.eventIcon, { backgroundColor: colors.gold }]}><Ionicons name="trophy-outline" size={20} color={colors.navy950} /></View><View style={{ flex: 1 }}><Text style={styles.eventTitle}>USN × {data.overview.upcomingMatches[0].opponent}</Text><Text style={styles.label}>{new Date(data.overview.upcomingMatches[0].kickoffAt).toLocaleString('ar-TN')}</Text></View></View></Card> : <Empty text={'لا توجد مباراة مبرمجة'} />}
    {data?.announcement && <><Text style={styles.section}>{'آخر إعلان'}</Text><Card><Text style={styles.announcementPriority}>{data.announcement.priority}</Text><Text style={styles.eventTitle}>{data.announcement.titleAr}</Text><Text style={styles.announcementBody}>{data.announcement.messageAr}</Text></Card></>}
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({ heading: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 }, kicker: { color: colors.gold, textAlign: 'right', fontSize: 10, fontWeight: '800', letterSpacing: 1 }, title: { color: colors.white, textAlign: 'right', fontSize: 27, fontWeight: '900', marginTop: 10 }, name: { color: colors.muted, textAlign: 'right', fontSize: 14, marginTop: 4 }, bell: { width: 43, height: 43, borderRadius: 13, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, badge: { position: 'absolute', top: -4, right: -4, minWidth: 18, height: 18, borderRadius: 9, backgroundColor: colors.red, color: colors.white, textAlign: 'center', fontSize: 10, fontWeight: '800', paddingHorizontal: 4 }, stats: { flexDirection: 'row-reverse', gap: 8, marginTop: 24 }, number: { color: colors.gold, fontSize: 22, fontWeight: '900', textAlign: 'right' }, label: { color: colors.muted, fontSize: 9, textAlign: 'right', marginTop: 4 }, section: { color: colors.white, fontWeight: '800', textAlign: 'right', fontSize: 16, marginTop: 25, marginBottom: 10 }, eventRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12 }, eventIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(243,189,34,.1)' }, eventTitle: { color: colors.white, fontSize: 14, fontWeight: '800', textAlign: 'right' }, announcementPriority: { color: colors.gold, textAlign: 'right', fontSize: 8, fontWeight: '900', marginBottom: 6 }, announcementBody: { color: colors.muted, textAlign: 'right', fontSize: 10, lineHeight: 18, marginTop: 7, marginBottom: 3 } });
