import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { request } from '@/src/api';
import { Empty, Screen } from '@/src/components';
import { useAuth } from '@/src/store';
import { colors } from '@/src/theme';
type Notification = { id: string; type: string; title: string; body: string; readAt?: string | null; createdAt: string };
export default function Notifications() {
  const token = useAuth((state) => state.token); const cache = useQueryClient(); const query = useQuery({ queryKey: ['mobile-notifications'], queryFn: () => request<{ data: Notification[]; meta: { unread: number } }>('/notifications', {}, token) });
  const read = useMutation({ mutationFn: (id: string) => request(`/notifications/${id}/read`, { method: 'PATCH' }, token), onSuccess: () => cache.invalidateQueries({ queryKey: ['mobile-notifications'] }) });
  const readAll = useMutation({ mutationFn: () => request('/notifications/read-all', { method: 'PATCH' }, token), onSuccess: () => cache.invalidateQueries({ queryKey: ['mobile-notifications'] }) });
  return <Screen><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => query.refetch()} tintColor={colors.gold} />}><View style={styles.heading}><View><Text style={styles.kicker}>{query.data?.meta.unread ?? 0} {'غير مقروء'}</Text><Text style={styles.title}>{'الإشعارات'}</Text></View>{Boolean(query.data?.meta.unread) && <Pressable style={styles.readAll} onPress={() => readAll.mutate()}><Ionicons name="checkmark-done" color={colors.gold} size={20} /></Pressable>}</View>{query.data?.data.length ? <View style={styles.list}>{query.data.data.map((item) => <Pressable key={item.id} style={[styles.item, !item.readAt && styles.unread]} onPress={() => !item.readAt && read.mutate(item.id)}><View style={styles.icon}><Ionicons name="notifications-outline" color={colors.gold} size={19} /></View><View style={styles.content}><Text style={styles.type}>{item.type}</Text><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.body}>{item.body}</Text><Text style={styles.date}>{new Date(item.createdAt).toLocaleString('ar-TN')}</Text></View>{!item.readAt && <View style={styles.dot} />}</Pressable>)}</View> : <Empty text={query.isLoading ? 'جار التحميل…' : 'لا توجد إشعارات'} />}</ScrollView></Screen>;
}
const styles = StyleSheet.create({ heading: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', marginTop: 8, marginBottom: 22 }, kicker: { color: colors.gold, textAlign: 'right', fontSize: 10, fontWeight: '800' }, title: { color: colors.white, textAlign: 'right', fontSize: 28, fontWeight: '900', marginTop: 7 }, readAll: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 12 }, list: { gap: 9 }, item: { flexDirection: 'row-reverse', gap: 12, padding: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.navy900, borderRadius: 16 }, unread: { borderColor: 'rgba(243,189,34,.3)', backgroundColor: colors.navy800 }, icon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: 'rgba(243,189,34,.1)' }, content: { flex: 1 }, type: { color: colors.gold, textAlign: 'right', fontSize: 8, fontWeight: '800' }, itemTitle: { color: colors.white, textAlign: 'right', fontSize: 13, fontWeight: '800', marginTop: 3 }, body: { color: colors.muted, textAlign: 'right', fontSize: 10, lineHeight: 17, marginTop: 4 }, date: { color: colors.muted, textAlign: 'right', fontSize: 8, marginTop: 7 }, dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.gold, marginTop: 5 } });
