import { useQuery } from '@tanstack/react-query';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { request } from '@/src/api';
import { Empty, Screen } from '@/src/components';
import { useAuth } from '@/src/store';
import { colors } from '@/src/theme';
type Player = { id: string; status: string; position?: string | null; person: { fullNameAr: string }; seasons: Array<{ jerseyNumber?: number | null; category: { nameAr: string } }> };
export default function Team() {
  const { token, user } = useAuth(); const query = useQuery({ queryKey: ['mobile-team', user?.id], queryFn: () => request<{ data: Player[] }>('/players/team', {}, token), enabled: Boolean(token && user?.permissions.includes('team.view')) });
  return <Screen><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => query.refetch()} tintColor={colors.gold} />}><Text style={styles.kicker}>USN SQUAD</Text><Text style={styles.title}>{'الفريق'}</Text><Text style={styles.subtitle}>{query.data?.data.length ?? 0} {'لاعب'}</Text>{query.data?.data.length ? <View style={styles.list}>{query.data.data.map((player) => <View style={styles.player} key={player.id}><View style={styles.avatar}><Text style={styles.initial}>{player.person.fullNameAr.slice(0, 1)}</Text></View><View style={styles.info}><Text style={styles.name}>{player.person.fullNameAr}</Text><Text style={styles.meta}>{player.seasons[0]?.category.nameAr ?? '—'} · {player.position ?? '—'}</Text></View><View style={styles.number}><Text>{player.seasons[0]?.jerseyNumber ?? '—'}</Text></View></View>)}</View> : <Empty text={query.isLoading ? 'جار التحميل…' : 'لا يوجد لاعبون مسجلون'} />}</ScrollView></Screen>;
}
const styles = StyleSheet.create({ kicker: { color: colors.gold, textAlign: 'right', fontSize: 10, fontWeight: '800', letterSpacing: 1.1, marginTop: 8 }, title: { color: colors.white, textAlign: 'right', fontSize: 29, fontWeight: '900', marginTop: 8 }, subtitle: { color: colors.muted, textAlign: 'right', fontSize: 11, marginTop: 5, marginBottom: 23 }, list: { gap: 8 }, player: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12, minHeight: 68, borderWidth: 1, borderColor: colors.line, borderRadius: 16, backgroundColor: colors.navy900, padding: 12 }, avatar: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.gold }, initial: { color: colors.navy950, fontSize: 17, fontWeight: '900' }, info: { flex: 1 }, name: { color: colors.white, textAlign: 'right', fontSize: 13, fontWeight: '800' }, meta: { color: colors.muted, textAlign: 'right', fontSize: 9, marginTop: 4 }, number: { width: 32, height: 32, borderRadius: 10, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' } });
