'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, CheckCheck } from 'lucide-react';
import { useParams } from 'next/navigation';
import { EmptyState, LoadingState } from '@usn/ui';
import { PageHeading } from '@/components/page-heading';
import { api } from '@/lib/api';
import type { WebLocale } from '@/i18n';
type Notification = { id: string; type: string; title: string; body: string; readAt?: string | null; createdAt: string };
export default function NotificationsPage() { const { locale } = useParams<{ locale: WebLocale }>(); const ar = locale === 'ar'; const cache = useQueryClient(); const query = useQuery({ queryKey: ['notifications'], queryFn: () => api<{ data: Notification[]; meta: { unread: number } }>('/notifications') }); const readAll = useMutation({ mutationFn: () => api('/notifications/read-all', { method: 'PATCH' }), onSuccess: () => cache.invalidateQueries({ queryKey: ['notifications'] }) }); const read = useMutation({ mutationFn: (id: string) => api(`/notifications/${id}/read`, { method: 'PATCH' }), onSuccess: () => cache.invalidateQueries({ queryKey: ['notifications'] }) }); return <><PageHeading eyebrow={`${query.data?.meta.unread ?? 0} ${ar ? 'غير مقروء' : 'non lues'}`} title={ar ? 'الإشعارات' : 'Notifications'} description={ar ? 'تنبيهات التدريبات والمباريات والإعلانات' : 'Alertes des entraînements, matchs et annonces'} action={<button className="ghost-button" onClick={() => readAll.mutate()} disabled={!query.data?.meta.unread}><CheckCheck size={16} />{ar ? 'تحديد الكل كمقروء' : 'Tout marquer comme lu'}</button>} />{query.isLoading ? <LoadingState label={ar ? 'جار التحميل…' : 'Chargement…'} /> : !query.data?.data.length ? <EmptyState title={ar ? 'لا توجد إشعارات' : 'Aucune notification'} message={ar ? 'أنت على اطلاع بكل شيء' : 'À jour !'} /> : <div className="notification-list">{query.data.data.map((item) => <button className={`notification-row ${item.readAt ? '' : 'notification-unread'}`} key={item.id} onClick={() => !item.readAt && read.mutate(item.id)}><span className="notification-icon"><Bell size={18} /></span><span><small>{item.type}</small><b>{item.title}</b><p>{item.body}</p></span><time>{new Intl.DateTimeFormat(ar ? 'ar-TN' : 'fr-TN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.createdAt))}</time></button>)}</div>}</>; }
