'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Globe2, KeyRound, Pencil, ShieldCheck, UsersRound, X } from 'lucide-react';
import { useParams } from 'next/navigation';
import { useState } from 'react';
import { LoadingState } from '@usn/ui';
import { PageHeading } from '@/components/page-heading';
import { api } from '@/lib/api';
import type { WebLocale } from '@/i18n';

type Category = { id: string; nameAr: string; nameFr: string };
type Permission = { id: string; key: string; description?: string | null };
type Role = { id: string; key: string; nameAr: string; nameFr: string; permissions: Array<{ permission: Permission }>; _count: { users: number } };
type Grant = { roleKey: string; isGlobal: boolean; categoryIds: string[] };
type User = { id: string; email: string; status: string; locale: string; person: { fullNameAr: string; firstName: string; lastName: string }; roles: Array<{ isGlobal: boolean; role: Role; scopes: Array<{ categoryId: string; category: Category }> }> };

export default function UsersPage() {
  const { locale } = useParams<{ locale: WebLocale }>(); const ar = locale === 'ar'; const cache = useQueryClient();
  const users = useQuery({ queryKey: ['users'], queryFn: () => api<{ data: User[] }>('/users') });
  const roles = useQuery({ queryKey: ['access-roles'], queryFn: () => api<{ data: Role[] }>('/users/roles') });
  const permissions = useQuery({ queryKey: ['access-permissions'], queryFn: () => api<{ data: Permission[] }>('/users/permissions') });
  const categories = useQuery({ queryKey: ['access-categories'], queryFn: () => api<{ data: Category[] }>('/users/scopes/categories') });
  const [editingUser, setEditingUser] = useState<User | null>(null); const [status, setStatus] = useState('ACTIVE'); const [grants, setGrants] = useState<Grant[]>([]);
  const [editingRole, setEditingRole] = useState<Role | null>(null); const [permissionDraft, setPermissionDraft] = useState<string[]>([]);
  const updateUser = useMutation({ mutationFn: () => api(`/users/${editingUser!.id}/access`, { method: 'PATCH', body: JSON.stringify({ status, roleGrants: grants }) }), onSuccess: async () => { await Promise.all([cache.invalidateQueries({ queryKey: ['users'] }), cache.invalidateQueries({ queryKey: ['session'] })]); setEditingUser(null); } });
  const updateRole = useMutation({ mutationFn: () => api(`/users/roles/${editingRole!.key}/permissions`, { method: 'PUT', body: JSON.stringify({ permissionKeys: permissionDraft }) }), onSuccess: async () => { await Promise.all([cache.invalidateQueries({ queryKey: ['access-roles'] }), cache.invalidateQueries({ queryKey: ['users'] }), cache.invalidateQueries({ queryKey: ['session'] })]); setEditingRole(null); } });
  const openUser = (user: User) => { setEditingUser(user); setStatus(user.status); setGrants(user.roles.map((grant) => ({ roleKey: grant.role.key, isGlobal: grant.isGlobal, categoryIds: grant.scopes.map((scope) => scope.categoryId) }))); };
  const toggleRole = (roleKey: string, checked: boolean) => setGrants((current) => checked ? [...current, { roleKey, isGlobal: false, categoryIds: [] }] : current.filter((grant) => grant.roleKey !== roleKey));
  const changeGrant = (roleKey: string, change: Partial<Grant>) => setGrants((current) => current.map((grant) => grant.roleKey === roleKey ? { ...grant, ...change } : grant));
  const toggleCategory = (roleKey: string, categoryId: string, checked: boolean) => setGrants((current) => current.map((grant) => grant.roleKey !== roleKey ? grant : { ...grant, categoryIds: checked ? [...grant.categoryIds, categoryId] : grant.categoryIds.filter((id) => id !== categoryId) }));
  const invalidGrants = grants.some((grant) => !['PLAYER', 'PARENT'].includes(grant.roleKey) && !grant.isGlobal && grant.categoryIds.length === 0);
  if (users.isLoading || roles.isLoading) return <LoadingState label={ar ? 'جار التحميل…' : 'Chargement…'} />;
  return <><PageHeading eyebrow="ACCESS CONTROL" title={ar ? 'المستخدمون والصلاحيات' : 'Utilisateurs et accès'} description={ar ? 'صلاحيات مباشرة ونطاق محدد لكل صنف' : 'Rôles et périmètres explicites par catégorie'} />
    <div className="access-stats"><div><UsersRound /><b>{users.data?.data.length ?? 0}</b><span>{ar ? 'مستخدم' : 'utilisateurs'}</span></div><div><ShieldCheck /><b>{roles.data?.data.length ?? 0}</b><span>{ar ? 'دور' : 'rôles'}</span></div><div><KeyRound /><b>{permissions.data?.data.length ?? 0}</b><span>{ar ? 'صلاحية' : 'permissions'}</span></div></div>
    <section className="data-card access-section"><div className="panel-title"><div><span className="eyebrow">USERS</span><h2>{ar ? 'حسابات النظام' : 'Comptes système'}</h2></div></div><div className="table-wrap"><table><thead><tr><th>{ar ? 'المستخدم' : 'Utilisateur'}</th><th>{ar ? 'الحالة' : 'Statut'}</th><th>{ar ? 'الأدوار' : 'Rôles'}</th><th /></tr></thead><tbody>{users.data?.data.map((user) => <tr key={user.id}><td><div className="person-cell"><span className="avatar">{user.person.fullNameAr.slice(0, 1)}</span><div><b>{ar ? user.person.fullNameAr : `${user.person.firstName} ${user.person.lastName}`}</b><small>{user.email}</small></div></div></td><td><span className={`access-status access-status--${user.status.toLowerCase()}`}>{user.status}</span></td><td><div className="grant-chips">{user.roles.map((grant) => <span key={grant.role.key}>{grant.role.key}{grant.isGlobal && <Globe2 size={11} />}{!grant.isGlobal && grant.scopes.length > 0 && <small>{grant.scopes.length}</small>}</span>)}</div></td><td><button className="ghost-button" onClick={() => openUser(user)}><Pencil size={14} />{ar ? 'إدارة' : 'Gérer'}</button></td></tr>)}</tbody></table></div></section>
    <section className="data-card access-section"><div className="panel-title"><div><span className="eyebrow">RBAC</span><h2>{ar ? 'الأدوار والصلاحيات' : 'Rôles et permissions'}</h2></div></div><div className="role-grid">{roles.data?.data.map((role) => <button key={role.id} onClick={() => { setEditingRole(role); setPermissionDraft(role.permissions.map((item) => item.permission.key)); }}><span>{role.key}</span><b>{ar ? role.nameAr : role.nameFr}</b><small>{role.permissions.length} permissions · {role._count.users} users</small></button>)}</div></section>
    {editingUser && <div className="access-overlay"><div className="access-editor"><button className="editor-close" onClick={() => setEditingUser(null)}><X /></button><span className="eyebrow">USER GRANTS</span><h2>{editingUser.person.fullNameAr}</h2><label className="editor-field"><span>{ar ? 'حالة الحساب' : 'Statut du compte'}</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option>ACTIVE</option><option>INVITED</option><option>SUSPENDED</option><option>DISABLED</option></select></label><div className="grant-editor">{roles.data?.data.map((role) => { const grant = grants.find((item) => item.roleKey === role.key); const membership = ['PLAYER', 'PARENT'].includes(role.key); return <div className="grant-row" key={role.key}><label><input type="checkbox" checked={Boolean(grant)} onChange={(event) => toggleRole(role.key, event.target.checked)} /><b>{role.key}</b></label>{grant && !membership && <><label className="global-check"><input type="checkbox" checked={grant.isGlobal} onChange={(event) => changeGrant(role.key, { isGlobal: event.target.checked, categoryIds: event.target.checked ? [] : grant.categoryIds })} /><Globe2 size={14} />{ar ? 'كل النادي' : 'Club entier'}</label>{!grant.isGlobal && <div className="scope-list">{categories.data?.data.map((category) => <label key={category.id}><input type="checkbox" checked={grant.categoryIds.includes(category.id)} onChange={(event) => toggleCategory(role.key, category.id, event.target.checked)} />{ar ? category.nameAr : category.nameFr}</label>)}</div>}</>}</div>; })}</div><button className="usn-button editor-save" onClick={() => updateUser.mutate()} disabled={updateUser.isPending || invalidGrants}>{updateUser.isPending ? '...' : ar ? 'حفظ الصلاحيات' : 'Enregistrer les accès'}</button>{invalidGrants && <p className="editor-error">{ar ? 'اختر نطاق صنف أو كامل النادي لكل دور.' : 'Choisissez une catégorie ou le club entier pour chaque rôle.'}</p>}{updateUser.isError && <p className="editor-error">{ar ? 'تعذر حفظ الصلاحيات' : "Impossible d'enregistrer"}</p>}</div></div>}
    {editingRole && <div className="access-overlay"><div className="access-editor"><button className="editor-close" onClick={() => setEditingRole(null)}><X /></button><span className="eyebrow">ROLE POLICY</span><h2>{editingRole.key}</h2><div className="permission-list">{permissions.data?.data.map((permission) => <label key={permission.id}><input type="checkbox" checked={permissionDraft.includes(permission.key)} onChange={(event) => setPermissionDraft((current) => event.target.checked ? [...current, permission.key] : current.filter((key) => key !== permission.key))} /><span><b>{permission.key}</b>{permission.description && <small>{permission.description}</small>}</span></label>)}</div><button className="usn-button editor-save" onClick={() => updateRole.mutate()} disabled={updateRole.isPending}>{ar ? 'حفظ سياسة الدور' : 'Enregistrer le rôle'}</button>{updateRole.isError && <p className="editor-error">{ar ? 'تعذر حفظ الدور' : "Impossible d'enregistrer"}</p>}</div></div>}
  </>;
}
